version: '3'
services:
  api:
    hostname: api
    build: .
    command: go run cmd/main.go
    environment:
      LINEBOT_CHANNEL_SECRET: "YOUR LINEBOT CHANNEL SECRET"
      LINEBOT_CHANNEL_ACCESS_TOKEN: "YOUR LINEBOT CHANNEL ACCESS TOKEN"
      RAKUTEN_APPLICATION_ID: "YOUR RAKUTEN APPLICATION ID"
    volumes:
    - ./:/go/src/github.com/YumaUeno123/linebot_go
    ports:
    - 8080:8080